CREATE TABLE DVD(
  TapeID  INTEGER NOT NULL,
  CategoryID  INTEGER NOT NULL,
  Title VARCHAR(50) NOT NULL,
  Year  YEAR NOT NULL,
  Cost DECIMAL(5,2) NOT NULL,
  RentedOut VARCHAR(5) NOT NULL,
  Rating  VARCHAR(5) NOT NULL,
  ActionOnReturn  VARCHAR(30) NOT NULL,
  CONSTRAINT PKTapeID PRIMARY KEY(TapeID),
  CONSTRAINT FKCategoryID FOREIGN KEY(CategoryID)
    REFERENCES MovieCategory(CategoryID)
);


CREATE TABLE MovieCategory(
  CategoryID  INTEGER NOT NULL,
  CategoryName  VARCHAR(50) NOT NULL,
  CONSTRAINT PKCategoryID PRIMARY KEY(CategoryID)
);

CREATE TABLE DVDRental(
  RentalID INTEGER NOT NULL,
  CustomerID CHAR(2) NOT NULL,
  TapeID INTEGER NOT NULL,
  RentalDate  DATE NOT NULL,
  CONSTRAINT PKRentalID PRIMARY KEY(RentalID),
  CONSTRAINT FKCustomerID FOREIGN KEY(CustomerID)
    REFERENCES CustomerList(CustomerID),
  CONSTRAINT FKTapeID FOREIGN KEY(TapeID)
    REFERENCES DVD(TapeID)
);

CREATE TABLE CustomerList(
  CustomerID CHAR(2) NOT NULL,
  FirstName VARCHAR(30) NOT NULL,
  LastName VARCHAR(30) NOT NULL,
  PhoneNumber CHAR(11) NOT NULL,
  BirthDate DATE NOT NULL,
  DriverLicenseNumber CHAR(10) NOT NULL,
  Status  VARCHAR(20),
  CONSTRAINT PKCustomerID PRIMARY KEY(CustomerID)
);
